### ISSUE TITLE
SOC system , the number of  bands (num_wann)

### ISSUE THREAD

**Issue by Lijiuyin** [Cloudiiink/pyw90#11]
Dear sir
Sorry to bother,  I found that the calculated EIGENVAL file with SOC is consistent with the non-spinful system, we know that with the SOC system, the number of energy bands should be doubled. For example, without SOC in wannier90, I need 78 bands. But with SOC, I need 156（value of num_wann ） bands, but I am running 'pyw90 pre dos --path . -e -4.85 20 --extra' command gives the following:
Dis frozen window table
The table is sorted according to the percentage of pdos/tdos.
If you want to see suggestion, please use menu.
dis_froz_min dis_froz_max N pdos tdos percent
14 2.738141 9.432657 78 78.269155 94.001511 0.832637
12 2.536791 8.672642 78 75.261777 91.590000 0.821725
15 2.754595 9.642980 78 75.859495 92.353371 0.821405
24 3.434191 10.819870 78 61.310056 74.819549 0.819439
13 2.678902 8.778362 78 71.441945 87.184462 0.819434...
The above parameter N only shows 78, I think it should affect the accuracy of the energy window here, I hope to get your guidance.
Thank you very much for your attention and support. I look forward to your response.dis_win_min(max)pyw90 eig suggest

Sincerely,
JiuYin Li

**Comment by Cloudiiink** [comment]
The `eig` menu offers a `deg` parameter, allowing manual adjustment of the desired number of Wannier functions. Setting `--deg 2` directly doubles the `num_wann` value.

However, it's worth noting that results derived from such window tables sometime exhibit instability during testing. A code restructuring and implementation of robust unit tests are planned to address this issue.

BTW, it is also recommended to utilize the command `pyw90 eig dist`. This command could display the distribution of eigenvalues. You can manual select appropriate energy windows from the output.

**Comment by Lijiuyin** [comment]
Dear Dr.Wang
Thanks for the reply, I'm sorry that I'm new to this field and still need to learn, I looked at README.md file, I tried the deg parameter and the energy windows given is really not very accurate, but i think the point of energy windows is dis_froz windows dis_froz windows，I use 'pyw90 pre dos --path .. -e -5 5 --rm-fermi' command to make sure I need the number of projections to be 156(num_wann) in the SOC system, and then I use 'pyw90 pre dos --path . -e -6.2 32 --extra 'Fe,0-5,0-8; Al,6-7,0-3; Te,8-11,0-3'' command to determine the value of dis_froz windows, as shown in the above result, the N parameter is shown as 78, here how can I double the num_wann？
Thank you very much for your attention and support.
Sincerely,
JiuYin Li

**Comment by Lijiuyin** [comment]
Okay
***@***.***




Dear Dr.WANG
Thank you very much for your reply and help, i am new to this field, there is a lot of knowledge to learn, i replied to you on GitHub and asked questions. I hope to get your guidance again.


Sincerely,
JiuYin Li



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cloudiiink/pyw90"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月24日(星期一) 晚上11:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Cloudiiink/pyw90] SOC system , the number of  bands (num_wann) (Issue #11)





 
The eig menu offers a deg parameter, allowing manual adjustment of the desired number of Wannier functions. Setting --deg 2 directly doubles the num_wann value.
 
However, it's worth noting that results derived from such window tables sometime exhibit instability during testing. A code restructuring and implementation of robust unit tests are planned to address this issue.
 
BTW, it is also recommended to utilize the command pyw90 eig dist. This command could display the distribution of eigenvalues. You can manual select appropriate energy windows from the output.

**Comment by Cloudiiink** [comment]
You can still use `--deg 2` to double `num_wann` with command `pyw90 pre dos --path . -e -6.2 32 --deg 2 --extra 'Fe,0-5,0-8; Al,6-7,0-3; Te,8-11,0-3'`.
