### ISSUE TITLE
the question

### ISSUE THREAD

**Issue by zc994646659** [Cloudiiink/pyw90#5]
The pyw90 cannot be installed with pip install pyw90? could this question be solved?

**Comment by Cloudiiink** [comment]
I have found that current version of pyw90 published in pypi is incompatible with Python 3.8.

I've resolved this issue in my github repository, but I have not yet published this version to pypi.
`pip install git+https://github.com/Cloudiiink/pyw90.git` can be used to install pyw90 if you have this installation issue.

**Comment by Cloudiiink** [comment]
The latest version `v1.0.7` has been uploaded to pypi with annotation problem fixed, so this issue will be closed.

If you have any other questions, please feel free to contact me or open new issue :)
