### ISSUE TITLE
pyw90 auto run issues

### ISSUE THREAD

**Issue by zc994646659** [Cloudiiink/pyw90#8]
when i run the command " pyw90 auto run "
it report TypeError: 'type' object is not subscriptable
does it need some input? why report this error? thank you for your advice.

**Comment by Cloudiiink** [comment]
Sorry for this problem. I have found that current version of pyw90 published in pypi is incompatible with Python 3.8.

I've resolved this issue in my github repository, but I have not yet published this version to pypi.
pip install git+https://github.com/Cloudiiink/pyw90.git can be used to install pyw90 if you have this installation issue.

**Comment by Cloudiiink** [comment]
The latest version `v1.0.7` has been uploaded to pypi, so this issue will be closed.

If you have any other questions, please feel free to contact me or open new issue :)
